### ISSUE TITLE
The child node "piwik_host" at path "webfactory_piwik" must be configured.

### ISSUE THREAD

**Issue by bperel** [webfactory/piwik-bundle#32]
Hello,

Thank you for this project. When trying to set it up for the first time I get the following error:
```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 216:
!!                                                                                
!!    The child node "piwik_host" at path "webfactory_piwik" must be configured.  
!!                                                                                
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

My configuration is located in `config/packages/matomo.yml` and contains:
```
webfactory_piwik:
    site_id: 1
    piwik_host: 'example.com'
    disabled: '%kernel.debug%'
    disable_cookies: true
```

Am I doing something wrong?
