### ISSUE TITLE
Support of multiple trackers

### ISSUE THREAD

**Issue by kachkaev** [webfactory/piwik-bundle#8]
I've seen a few cases when people were willing to use multiple trackers in their apps. It would be nice if your repository could support them too in a way. The config would look like this:
```yml
webfactory_piwik:
    main:
        site_id: 1
        disabled: %kernel.debug%
        piwik_host: my.piwik.hostname
       tracker_path: "/js/"
    other:
        site_id: 42
        disabled: %kernel.debug%
        piwik_host: example.com
        tracker_path: "/analytics/"
```
If this ever gets implemented, service names in #7 would have to be made different too:
```php
$tracker1 = $container->get('webfactory_piwik.tracker.main');
$tracker2 = $container->get('webfactory_piwik.tracker.other');
```
